# Generated by Django 4.2.7 on 2025-08-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa galerii')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
            ],
            options={
                'verbose_name': 'Zbiór zdjęć',
                'verbose_name_plural': 'Zbiory zdjęć',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', verbose_name='Zdjęcie')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.galleryset')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
                'ordering': ['order', 'id'],
            },
        ),
    ]
