# Generated by Django 4.2.7 on 2025-08-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gallery/')),
                ('media_type', models.CharField(choices=[('image', 'Zdjęcie'), ('video', 'Wideo')], editable=False, max_length=5)),
                ('order', models.PositiveIntegerField(default=1)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='gallery.gallery')),
            ],
            options={
                'verbose_name': 'Plik multimedialny',
                'verbose_name_plural': 'Pliki multimedialne',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
