# Generated by Django 4.2.7 on 2025-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryset',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerie'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='gallery_set',
            new_name='gallery',
        ),
        migrations.RemoveField(
            model_name='galleryset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AlterField(
            model_name='galleryset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='galleryset',
            name='name',
            field=models.CharField(help_text='Tylko nazwa do identyfikacji', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Po prostu wrzuć zdjęcie', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Kolejność (0, 1, 2...)'),
        ),
    ]
