# Generated by Django 4.2.7 on 2025-08-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_alter_photo_options_remove_photo_created_at_and_more'),
        ('main', '0011_alter_dog_certificates_gallery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GallerySet',
        ),
    ]
