# Generated by Django 4.2.7 on 2025-08-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_delete_galleryset'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nazwa galerii'),
        ),
    ]
