# Generated by Django 4.2.7 on 2025-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='vertical_position',
            field=models.IntegerField(default=50, help_text='Pozycja pionowa 0-100'),
        ),
    ]
