# Generated by Django 4.2.7 on 2025-08-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
