# Generated by Django 4.2.7 on 2025-08-16 10:47

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(blank=True, upload_to='about/', verbose_name='Zdjęcie główne')),
                ('certificates_gallery', models.ForeignKey(blank=True, help_text='Certyfikaty hodowli, nagrody, dyplomy itp.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_certificates', to='gallery.gallery', verbose_name='Galeria certyfikatów')),
            ],
            options={
                'verbose_name': 'Strona O nas',
                'verbose_name_plural': 'Strona O nas',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.aboutpage')),
            ],
            options={
                'verbose_name': 'Sekcja',
                'verbose_name_plural': 'Sekcje',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(unique=True, verbose_name='URL (slug)')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Krótki opis')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowane')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('photo_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='gallery.gallery', verbose_name='Galeria zdjęć')),
            ],
            options={
                'verbose_name': 'Wpis na blogu',
                'verbose_name_plural': 'Wpisy na blogu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data wysłania')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytane')),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('gender', models.CharField(choices=[('male', 'Pies'), ('female', 'Suka')], max_length=10, verbose_name='Płeć')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('is_breeding', models.BooleanField(default=False, verbose_name='Pies hodowlany')),
                ('certificates_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_certificates', to='gallery.gallery', verbose_name='Galeria certyfikatów')),
                ('photo_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_photos', to='gallery.gallery', verbose_name='Galeria zdjęć')),
            ],
            options={
                'verbose_name': 'Pies',
                'verbose_name_plural': 'Psy',
                'ordering': ['name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('mother_name', models.CharField(blank=True, help_text='Imię matki - tylko do wyświetlania', max_length=100, verbose_name='Matka')),
                ('father_name', models.CharField(blank=True, help_text='Imię ojca - tylko do wyświetlania', max_length=100, verbose_name='Ojciec')),
                ('litter', models.CharField(default='A', help_text='Jedna litera oznaczająca miot (A, B, C...)', max_length=1, verbose_name='Miot')),
                ('color1', colorfield.fields.ColorField(default='#FFFFFF', help_text='Pierwszy kolor', image_field=None, max_length=25, samples=None, verbose_name='Kolor 1')),
                ('color2', colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='Drugi kolor (opcjonalny)', image_field=None, max_length=25, samples=None, verbose_name='Kolor 2')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('gender', models.CharField(choices=[('male', 'Pies'), ('female', 'Suka')], max_length=10, verbose_name='Płeć')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępne')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('certificates_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppy_certificates', to='gallery.gallery', verbose_name='Galeria certyfikatów')),
                ('photo_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppy_photos', to='gallery.gallery', verbose_name='Galeria zdjęć')),
            ],
            options={
                'verbose_name': 'Szczeniak',
                'verbose_name_plural': 'Szczeniaki',
                'ordering': ['litter'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='Wiadomość')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data zgłoszenia')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('confirmed', 'Potwierdzone'), ('cancelled', 'Anulowane')], default='pending', max_length=20, verbose_name='Status')),
                ('puppy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.puppy', verbose_name='Szczeniak')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tytuł sekcji')),
                ('content', models.TextField(verbose_name='Treść sekcji')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.blogpost', verbose_name='Wpis na blogu')),
            ],
            options={
                'verbose_name': 'Sekcja wpisu',
                'verbose_name_plural': 'Sekcje wpisu',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PuppyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('breed', models.CharField(max_length=100, verbose_name='Rasa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.puppy')),
            ],
            options={
                'verbose_name': 'Szczeniak Translation',
                'db_table': 'main_puppy_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DogTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('breed', models.CharField(max_length=100, verbose_name='Rasa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.dog')),
            ],
            options={
                'verbose_name': 'Pies Translation',
                'db_table': 'main_dog_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutSectionsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Nagłówek H3')),
                ('content', models.TextField(verbose_name='Treść paragrafu')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.aboutsections')),
            ],
            options={
                'verbose_name': 'Sekcja Translation',
                'db_table': 'main_aboutsections_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('main_title', models.CharField(max_length=200, verbose_name='Główny tytuł')),
                ('quote_text', models.TextField(blank=True, verbose_name='Tekst cytatu')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.aboutpage')),
            ],
            options={
                'verbose_name': 'Strona O nas Translation',
                'db_table': 'main_aboutpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
