# Generated by Django 4.2.7 on 2025-07-09 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data wysłania')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytane')),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('breed', models.CharField(max_length=100, verbose_name='Rasa')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('gender', models.CharField(choices=[('male', 'Pies'), ('female', 'Suka')], max_length=10, verbose_name='Płeć')),
                ('description', models.TextField(verbose_name='Opis')),
                ('photo', models.ImageField(upload_to='dogs/', verbose_name='Zdjęcie')),
                ('is_breeding', models.BooleanField(default=False, verbose_name='Pies hodowlany')),
            ],
            options={
                'verbose_name': 'Pies',
                'verbose_name_plural': 'Psy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('gender', models.CharField(choices=[('male', 'Pies'), ('female', 'Suka')], max_length=10, verbose_name='Płeć')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('photo', models.ImageField(upload_to='puppies/', verbose_name='Zdjęcie')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępne')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puppies_as_father', to='main.dog', verbose_name='Ojciec')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puppies_as_mother', to='main.dog', verbose_name='Matka')),
            ],
            options={
                'verbose_name': 'Szczeniak',
                'verbose_name_plural': 'Szczeniaki',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='Wiadomość')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data zgłoszenia')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('confirmed', 'Potwierdzone'), ('cancelled', 'Anulowane')], default='pending', max_length=20, verbose_name='Status')),
                ('puppy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.puppy', verbose_name='Szczeniak')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(unique=True, verbose_name='URL (slug)')),
                ('content', models.TextField(verbose_name='Treść')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Krótki opis')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Zdjęcie główne')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowane')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Wpis na blogu',
                'verbose_name_plural': 'Wpisy na blogu',
                'ordering': ['-created_at'],
            },
        ),
    ]
