# Generated by Django 4.2.7 on 2025-07-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Certyfikat'),
        ),
    ]
