# Generated by Django 4.2.7 on 2025-08-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena zaproponowana przez klienta (PLN)', max_digits=10, null=True, verbose_name='Proponowana cena'),
        ),
    ]
