# Generated by Django 4.2.7 on 2025-08-16 10:30

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='quote_text',
        ),
        migrations.RemoveField(
            model_name='aboutsections',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aboutsections',
            name='title',
        ),
        migrations.CreateModel(
            name='AboutSectionsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Nagłówek H3')),
                ('content', models.TextField(verbose_name='Treść paragrafu')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.aboutsections')),
            ],
            options={
                'verbose_name': 'Sekcja Translation',
                'db_table': 'main_aboutsections_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('main_title', models.CharField(max_length=200, verbose_name='Główny tytuł')),
                ('quote_text', models.TextField(blank=True, verbose_name='Tekst cytatu')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.aboutpage')),
            ],
            options={
                'verbose_name': 'Strona O nas Translation',
                'db_table': 'main_aboutpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
