# Generated by Django 4.2.7 on 2025-08-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_dog',
            field=models.ForeignKey(blank=True, help_text='Wybierz psa, którego dotyczy ten wpis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='main.dog', verbose_name='Powiązany pies'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_puppy',
            field=models.ForeignKey(blank=True, help_text='Wybierz szczeniaka, którego dotyczy ten wpis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='main.puppy', verbose_name='Powiązany szczeniak'),
        ),
    ]
