# Generated by Django 4.2.7 on 2025-07-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dog_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200, verbose_name='Główny tytuł')),
                ('quote_text', models.TextField(blank=True, verbose_name='Tekst cytatu')),
                ('top_image', models.ImageField(blank=True, upload_to='about/', verbose_name='Zdjęcie główne')),
            ],
            options={
                'verbose_name': 'Strona O nas',
                'verbose_name_plural': 'Strona O nas',
            },
        ),
        migrations.CreateModel(
            name='AboutSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Nagłówek H3')),
                ('content', models.TextField(verbose_name='Treść paragrafu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.aboutpage')),
            ],
            options={
                'verbose_name': 'Sekcja',
                'verbose_name_plural': 'Sekcje',
                'ordering': ['order'],
            },
        ),
    ]
