# Generated by Django 4.2.7 on 2025-08-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogpost_related_dog_blogpost_related_puppy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='mother_name',
        ),
        migrations.AddField(
            model_name='puppy',
            name='father',
            field=models.ForeignKey(blank=True, help_text='Wybierz ojca z istniejących psów w bazie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppy_children_as_father', to='main.dog', verbose_name='Ojciec (z bazy)'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='father_name_custom',
            field=models.CharField(blank=True, help_text='Imię ojca - jeśli nie ma go w bazie psów', max_length=100, verbose_name='Ojciec (imię własne)'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='mother',
            field=models.ForeignKey(blank=True, help_text='Wybierz matkę z istniejących psów w bazie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppy_children_as_mother', to='main.dog', verbose_name='Matka (z bazy)'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='mother_name_custom',
            field=models.CharField(blank=True, help_text='Imię matki - jeśli nie ma jej w bazie psów', max_length=100, verbose_name='Matka (imię własne)'),
        ),
    ]
