# Generated by Django 4.2.7 on 2025-07-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutpage_aboutsections'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Certyfikat'),
        ),
    ]
