# Generated by Django 4.2.7 on 2025-08-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_puppy_father_name_remove_puppy_mother_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
    ]
