# Generated by Django 4.2.7 on 2025-07-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_puppy_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(upload_to='dogs/', verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='photo',
            field=models.ImageField(upload_to='puppies/', verbose_name='Zdjęcie główne'),
        ),
        migrations.CreateModel(
            name='PuppyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='puppies/', verbose_name='Zdjęcie')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Opis zdjęcia')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('puppy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.puppy', verbose_name='Szczeniak')),
            ],
            options={
                'verbose_name': 'Zdjęcie szczeniaka',
                'verbose_name_plural': 'Zdjęcia szczeniąt',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dogs/', verbose_name='Zdjęcie')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Opis zdjęcia')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.dog', verbose_name='Pies')),
            ],
            options={
                'verbose_name': 'Zdjęcie psa',
                'verbose_name_plural': 'Zdjęcia psów',
                'ordering': ['order'],
            },
        ),
    ]
