# Generated by Django 4.2.7 on 2025-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dog_photo_alter_puppy_photo_puppyimages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppyimages',
            name='puppy',
        ),
        migrations.AddField(
            model_name='dog',
            name='additional_photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Dodatkowe zdjęcia'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='additional_photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Dodatkowe zdjęcia'),
        ),
        migrations.DeleteModel(
            name='DogImages',
        ),
        migrations.DeleteModel(
            name='PuppyImages',
        ),
    ]
