# Generated by Django 4.2.7 on 2025-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_puppyimages_puppy_dog_additional_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='additional_photos',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='additional_photos',
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='photo',
        ),
        migrations.AddField(
            model_name='dog',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Zdjęcia'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Zdjęcia'),
        ),
    ]
