# Generated by Django 4.2.7 on 2025-07-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_dog_additional_photos_remove_dog_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='certificates',
            field=models.JSONField(blank=True, default=list, verbose_name='Certyfikaty'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='certificates',
            field=models.JSONField(blank=True, default=list, verbose_name='Certyfikaty'),
        ),
    ]
