# Generated by Django 4.2.7 on 2025-08-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('main', '0008_dog_certificates_puppy_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photos',
        ),
        migrations.AddField(
            model_name='dog',
            name='photo_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.galleryset', verbose_name='Galeria zdjęć'),
        ),
    ]
