# Generated by Django 4.2.7 on 2025-08-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('main', '0009_remove_dog_photos_dog_photo_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='photos',
        ),
        migrations.AddField(
            model_name='dog',
            name='certificates_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_certificates', to='gallery.galleryset', verbose_name='Galeria certyfikatów'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='certificates_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppy_certificates', to='gallery.galleryset', verbose_name='Galeria certyfikatów'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='photo_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppy_photos', to='gallery.galleryset', verbose_name='Galeria zdjęć'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_photos', to='gallery.galleryset', verbose_name='Galeria zdjęć'),
        ),
    ]
