# Generated by Django 4.2.7 on 2025-08-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_alter_photo_options_remove_photo_created_at_and_more'),
        ('main', '0010_remove_dog_certificates_remove_puppy_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='certificates_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_certificates', to='gallery.gallery', verbose_name='Galeria certyfikatów'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_photos', to='gallery.gallery', verbose_name='Galeria zdjęć'),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='certificates_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppy_certificates', to='gallery.gallery', verbose_name='Galeria certyfikatów'),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='photo_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppy_photos', to='gallery.gallery', verbose_name='Galeria zdjęć'),
        ),
    ]
