# Generated by Django 4.2.7 on 2025-08-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_delete_galleryset'),
        ('main', '0011_alter_dog_certificates_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='gallery.gallery', verbose_name='Galeria zdjęć'),
        ),
    ]
