# Generated by Django 4.2.7 on 2025-08-07 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tytuł sekcji')),
                ('content', models.TextField(verbose_name='Treść sekcji')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.blogpost', verbose_name='Wpis na blogu')),
            ],
            options={
                'verbose_name': 'Sekcja wpisu',
                'verbose_name_plural': 'Sekcje wpisu',
                'ordering': ('order',),
            },
        ),
    ]
