# Generated by Django 4.2.7 on 2025-08-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_blogpost_content_blogsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puppy',
            options={'ordering': ['litter', 'name'], 'verbose_name': 'Szczeniak', 'verbose_name_plural': 'Szczeniaki'},
        ),
        migrations.AddField(
            model_name='puppy',
            name='litter',
            field=models.CharField(default='A', help_text='Jedna litera oznaczająca miot (A, B, C...)', max_length=1, verbose_name='Miot'),
        ),
    ]
