# Generated by Django 4.2.7 on 2025-08-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_puppy_options_puppy_litter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='father',
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='mother',
        ),
        migrations.AddField(
            model_name='puppy',
            name='father_name',
            field=models.CharField(blank=True, help_text='Imię ojca - tylko do wyświetlania', max_length=100, verbose_name='Ojciec'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='mother_name',
            field=models.CharField(blank=True, help_text='Imię matki - tylko do wyświetlania', max_length=100, verbose_name='Matka'),
        ),
    ]
