# Generated by Django 4.2.7 on 2025-08-08 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_delete_galleryset'),
        ('main', '0015_remove_puppy_father_remove_puppy_mother_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='certificates_gallery',
            field=models.ForeignKey(blank=True, help_text='Certyfikaty hodowli, nagrody, dyplomy itp.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_certificates', to='gallery.gallery', verbose_name='Galeria certyfikatów'),
        ),
    ]
