# Generated by Django 4.2.7 on 2025-08-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_aboutpage_certificates_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='color1',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Pierwszy kolor (hex)', max_length=7, verbose_name='Kolor 1'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='color2',
            field=models.CharField(blank=True, default='', help_text='Drugi kolor (hex, opcjonalny)', max_length=7, verbose_name='Kolor 2'),
        ),
    ]
