# Generated by Django 4.2.7 on 2025-08-13 14:50

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_puppy_color1_puppy_color2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['translations__name'], 'verbose_name': 'Pies', 'verbose_name_plural': 'Psy'},
        ),
        migrations.RemoveField(
            model_name='dog',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='name',
        ),
        migrations.AlterField(
            model_name='puppy',
            name='color1',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Pierwszy kolor', image_field=None, max_length=25, samples=None, verbose_name='Kolor 1'),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='color2',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='Drugi kolor (opcjonalny)', image_field=None, max_length=25, samples=None, verbose_name='Kolor 2'),
        ),
        migrations.CreateModel(
            name='DogTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('breed', models.CharField(max_length=100, verbose_name='Rasa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.dog')),
            ],
            options={
                'verbose_name': 'Pies Translation',
                'db_table': 'main_dog_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
