# Generated by Django 4.2.7 on 2025-08-09 21:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_puppy_color1_puppy_color2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='main_title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Główny tytuł (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='quote_text_en',
            field=models.TextField(blank=True, verbose_name='Tekst cytatu (EN)'),
        ),
        migrations.AddField(
            model_name='aboutsections',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Treść paragrafu (EN)'),
        ),
        migrations.AddField(
            model_name='aboutsections',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nagłówek H3 (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Krótki opis (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_en',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL (slug) (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tytuł (EN)'),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Treść sekcji (EN)'),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tytuł sekcji (EN)'),
        ),
        migrations.AddField(
            model_name='dog',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Opis (EN)'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Opis (EN)'),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='color1',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Pierwszy kolor', image_field=None, max_length=25, samples=None, verbose_name='Kolor 1'),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='color2',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='Drugi kolor (opcjonalny)', image_field=None, max_length=25, samples=None, verbose_name='Kolor 2'),
        ),
    ]
