# Generated by Django 4.2.7 on 2025-08-31 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('owner_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('owner_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Telefon')),
                ('dog_name', models.CharField(max_length=50, verbose_name='Imię psa')),
                ('dog_breed', models.CharField(max_length=50, verbose_name='Rasa')),
                ('dog_age', models.PositiveIntegerField(verbose_name='Wiek psa')),
                ('date_from', models.DateField(verbose_name='Data rozpoczęcia')),
                ('date_to', models.DateField(verbose_name='Data zakończenia')),
                ('additional_services', models.TextField(blank=True, verbose_name='Usługi dodatkowe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Pytanie')),
                ('answer', models.TextField(verbose_name='Odpowiedź')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
    ]
